packages:
  ruby: 1.8.7-p72
  readline: 6.0
  rubygems: 1.3.1
gems:
  sqlite3-ruby: 1.2.4
  json: 1.1.4
  rake: 0.8.6
  mongrel: 1.1.5
  rspec-rails: 1.2.6
  rack: 1.0.0
  spicycode-rcov: 0.8.2.1
  capistrano: 2.5.5
  capistrano-ext: 1.2.1
  mocha: 0.9.5
